import { KeyCode } from "./KeyCode";

export const keyCodeByChar: Record<string, KeyCode> = {
  a: KeyCode.KeyA,
  b: KeyCode.KeyB,
  c: KeyCode.KeyC,
  d: KeyCode.KeyD,
  e: KeyCode.KeyE,
  f: KeyCode.KeyF,
  g: KeyCode.KeyG,
  h: KeyCode.KeyH,
  i: KeyCode.KeyI,
  j: KeyCode.KeyJ,
  k: KeyCode.KeyK,
  l: KeyCode.KeyL,
  m: KeyCode.KeyM,
  n: KeyCode.KeyN,
  o: KeyCode.KeyO,
  p: KeyCode.KeyP,
  q: KeyCode.KeyQ,
  r: KeyCode.KeyR,
  s: KeyCode.KeyS,
  t: KeyCode.KeyT,
  u: KeyCode.KeyU,
  v: KeyCode.KeyV,
  w: KeyCode.KeyW,
  x: KeyCode.KeyX,
  y: KeyCode.KeyY,
  z: KeyCode.KeyZ,
};
