import { KeyCode } from "./KeyCode";

export const letterKeys = [
  KeyCode.KeyA,
  KeyCode.KeyB,
  KeyCode.KeyC,
  KeyCode.KeyD,
  KeyCode.KeyE,
  KeyCode.KeyF,
  KeyCode.KeyG,
  KeyCode.KeyH,
  KeyCode.KeyI,
  KeyCode.KeyJ,
  KeyCode.KeyK,
  KeyCode.KeyL,
  KeyCode.KeyM,
  KeyCode.KeyN,
  KeyCode.KeyO,
  KeyCode.KeyP,
  KeyCode.KeyQ,
  KeyCode.KeyR,
  KeyCode.KeyS,
  KeyCode.KeyT,
  KeyCode.KeyU,
  KeyCode.KeyV,
  KeyCode.KeyW,
  KeyCode.KeyX,
  KeyCode.KeyY,
  KeyCode.KeyZ,
];
